version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=admin
    networks:
      - url-shortener

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3000:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/
    networks:
      - url-shortener
    
  app:
    image: app 
    build: 
      context: .
    ports: 
      - "9090:8080"
    environment:
      - PORT=${PORT}
    depends_on:
      - mongo
    networks:
      - url-shortener
networks:
    url-shortener:
        driver: bridge
        name: url-shortener